### ISSUE TITLE
reverse problem

### ISSUE THREAD

**Issue by mustafabereket** [frapontillo/angular-gage#12]
Hi There,

So I need to use these gages in reverse order and I am pretty sure I have the most updated version. However, for some reason when I add `reverse="true"` it doesnt change anything. I wonder why.

Here is my html:
`<justgage decimals="true" reverse="true" title-min-font-size="12" class="col-md-2 col-sm-2" ng-if="!dashboardCtrl.metric" id="test1" min=0 max=140 value="{{device.tc1}}" custom-sectors="{{device.customSectors}}" title="{{device.title}}" width="155" height="155" symbol="°F"></justgage>
`

Also, I tried sending boolean check for reverse from javascript like "reverse={{device.reverseCheck}}" but it didnt work either.

Thanks

**Comment by frapontillo** [comment]
The `reverse` attribute hasn't been released yet. If you want to use it you need to reference the #develop branch on bower.

**Comment by frapontillo** [comment]
See #11
