### ISSUE TITLE
"decimals" does not affect min/max values

### ISSUE THREAD

**Issue by LanderN** [frapontillo/angular-gage#13]
There also seems to be a bug that causes the background not to be drawn

``` html
<div justgage
         value="{{(disk.total-disk.free)/1000000000}}" 
         min="0" max="{{disk.total/1000000000}}"
         hide-inner-shadow="true"
         decimals="0"
         symbol="GB"></div>
```

results in: 
![](https://i.imgur.com/PNchA4b.png)
while

``` html
<div justgage
         value="{{(disk.total-disk.free)/1000000000}}" 
         min="0" max="3000"
         hide-inner-shadow="true"
         decimals="0"
         symbol="GB"></div>
```

results in
![](https://i.imgur.com/dsJQ0at.png)

``` javascript
$scope.disk = {total: 3000591806464, free: 444170838016};
```

**Comment by frapontillo** [comment]
Looks like a bug to me, but I really have no time to allocate on this project anymore, I'd be glad if you find the issue and open a PR against it. Thanks.

**Comment by frapontillo** [comment]
Oh BTW, I think that `decimals` applies only to your value, not the min or max. You can use a custom filter to round your `max` number and be done with it.

With regards to the background, again, I would appreciate it if you could debug it.
