### ISSUE TITLE
Gage doesn't redraw when hidden/brought into view

### ISSUE THREAD

**Issue by dnfield** [frapontillo/angular-gage#16]
This is related to https://github.com/toorshia/justgage/issues/93

I've fixed this here: https://github.com/dnfield/angular-gage/blob/develop/src/directives/justgage.js

However, I didn't update the dist folder or rebuild anything - would you like me to create a pull request for this?

**Comment by frapontillo** [comment]
Go ahead and open the PR please, I cannot see the diff from there. 👍
